### ISSUE TITLE
"no messages in inbox" even though there are

### ISSUE THREAD

**Issue by SnooPac** [StevenMaude/go-mailin8#47]
``./go-mailin8_linux_amd64 test@mailinator.com``
``Retrieving URL: https://inboxes.com/api/v2/inbox/test@mailinator.com``
``no messages in inbox``

There are messages in test@mailinator.com.

Also, assuming that works, is there a way to show the contents of a specific email from the list that comes back?

**Comment by StevenMaude** [comment]
:wave: Thanks for reporting the issue.

The — slightly tedious — history is that:

1. This application used to work with `mailinator.com`, so it was called `go-mailin8`
2. `mailinator.com` redesigned their site into some more complicated WebSocket-based application a while ago, breaking this application
3. This application switched to using the `getnada` site
4. `getnada` became `inboxes.com`, breaking this application again
5. This application switched to using `inboxes.com`

If you use an address as provided by `inboxes.com`, that should still work. Please open another issue if not :sunglasses:

***
 
> is there a way to show the contents of a specific email from the list that comes back?

No, not right now. I noted it down in #12, but never got round to it.

For my use, I tend to only use a one-off email address once, and this works fine for that.

**Comment by SnooPac** [comment]
Hah my bad.
I guess I didn't "dig through" (aka read the 1st line of) the documentation well enough.

Thanks for the quick reply.

**Comment by StevenMaude** [comment]
No problem; thanks for taking a look at this project :+1:
